INSERT INTO bikeshedapp_brand VALUES (1, 'Cannondale', 'http://www.vintagecannondale.com/cannondale/Logos/cannondale%20logo.png');
INSERT INTO bikeshedapp_brand VALUES (2, 'Cervelo', 'https://wemakerunningcool.files.wordpress.com/2014/01/cervelo-logo.jpg');
INSERT INTO bikeshedapp_brand VALUES (3, 'Colnago', 'https://seeklogo.com/images/C/Colnago-logo-BE7C1FBA94-seeklogo.com.gif');
INSERT INTO bikeshedapp_brand VALUES (4, 'Parlee', 'http://veloswap.competitor.com/files/2014/10/Parlee-Logo.jpg');
INSERT INTO bikeshedapp_brand VALUES (5, 'Jamis', 'https://cyclesoflifepb.files.wordpress.com/2011/10/jamis-logo1.jpg');

INSERT INTO auth_user VALUES (1, 'test_user', '2017-01-16 12:12:36.366495-05', true, 'test_user', 'test', 'user', 'test@user.com', true, true, '2017-01-16 12:12:36.366495-05');

INSERT INTO bikeshedapp_bike VALUES (1, 'H', '2017-01-16 12:12:36.366495-05', 'Quick Speed 3 Bike', 'Flat handlebar and upright riding position allow good visibility while riding', 'Designed for everyday riding and longer weekend excursions, the Quick Speed 3 bike combines a comfort-oriented geometry with lightweight materials to deliver both comfort and speed.', 'uploads/cannondale_quick_speed_3.jpeg', 25, 799.99, 1, 1);
INSERT INTO bikeshedapp_bike VALUES (2, 'M', '2017-01-16 12:12:36.366495-05', 'CAAD12 Disc 105 5 Bike', 'This bike is for aspiring racers', 'Think you know aluminum? Think again. Incomparably light, explosively stiff and impossibly smooth, the CAAD12 Disc 105 redefines performance with the finest alloy racing bike ever made by Cannondale.', 'uploads/CAAD12.jpeg', 25, 1849.00, 1, 1);
INSERT INTO bikeshedapp_bike VALUES (3, 'R', '2017-01-16 12:12:36.366495-05', 'Quick Althea 2 Womens Bike', 'Flat handlebar and upright riding position allow good visibility while riding', 'Tackle a variety of surfaces for all-day fun with the Cannondale Quick Althea 2 bike. Knobby tires and a combination of road and mountain bike design take you from road to gravel with ease.', 'uploads/althea_womens.jpeg', 25, 599.95, 1, 1);

INSERT INTO bikeshedapp_bike VALUES (4, 'H', '2017-01-16 12:12:36.366495-05', 'P5 Three Dura-Ace', 'The P5 is not only faster, but it also fits better.', 'The P5 is Cervélo’s latest creation, bringing to the world the most advanced and the most aerodynamic triathlon/TT bike possible. Designed using Formula 1-level Computational Fluid Dynamics software (CFD) and proven in the wind tunnel, the P5 is six to 11 watts faster than other so-called “superbikes”.', 'uploads/dura_ace.jpg', 25, 3999.99, 2, 1);
INSERT INTO bikeshedapp_bike VALUES (5, 'M', '2017-01-16 12:12:36.366495-05', 'Blue Triad SP 105', 'Starting at $106 a month. Learn More', ' Constructed with our proprietary Sport Performance high-modulus carbon fiber BB30 bottom bracket shell SFT2 Super Flow Tube Technology: fork, down tube and seat stay cross sections oriented to the direction the wind flows across bike Drop Down Tube design for improved aerodynamic interface between front wheel.', 'uploads/sp_105.jpeg', 25, 1199.99, 2, 1);
INSERT INTO bikeshedapp_bike VALUES (6, 'R', '2017-01-16 12:12:36.366495-05', 'SHIMANO A050 Double Disc', 'A truly great bike', 'For when you want a game-changing advantage, no matter what challenges the road throws at you. Over 100 unique frame iterations were built in layup development alone to perfect the new A050. Our road-tested aero features make the A050 faster in the real world, not just in the wind tunnel.', 'uploads/shimano.jpeg', 25, 499.99, 2, 1);

INSERT INTO bikeshedapp_bike VALUES (7, 'H', '2017-01-16 12:12:36.366495-05', 'A1r 105', 'Every feature has been thoroughly studied and designed, following the legendary Colnago criteria.', 'A lot went into the design of the A1r. Close attention was paid to the orientation of tube junctions with the goal of ensuring maximum torsional rigidity without sacrificing comfort. The theme of comfort without sacrificing performance is a major one for the Colnago brand.', 'uploads/COLNAGO-A1r-A1WK.jpg', 25, 1699.95, 3, 1);
INSERT INTO bikeshedapp_bike VALUES (8, 'M', '2017-01-16 12:12:36.366495-05', 'Prestige - 15', 'Lugged construction fitting accommodates custom rider fit and preferences.', 'From the full-width bottom bracket lug which connects them to the monocoque front triangle to the neatly machined replaceable dropouts, the chainstays morph from a deep rectangular profile to a compact square profile, the end result of which is the race ready ride we enjoyed so much.', 'uploads/prestige.jpg', 25, 2669.95, 3, 1);
INSERT INTO bikeshedapp_bike VALUES (9, 'R', '2017-01-16 12:12:36.366495-05', 'Concept', 'Colnago unveiled its first ever aero bike in a little castle in Germany just up the road from Eurobike. ', 'Concept and every other bike he produces is “to make cyclists faster.” And he delivered on that promise. So now there are three bikes occupying that highest rung in the Colnago hierarchy: The C60, V1r and the Colnago Concept.', 'uploads/concept_chrd.jpg', 25, 4599.95, 3, 1);

INSERT INTO bikeshedapp_bike VALUES (10, 'H', '2017-01-16 12:12:36.366495-05', 'Chebacco', 'ONE BIKE. ENDLESS POSSIBILITIES.', 'It’s inspired by a place where history runs deep. North of Boston, in the county now known as Essex, Chebacco Parish was one of the earliest European settlements in the mid-1600s.', 'uploads/34-chebacco.jpg', 25, 3799.99, 4, 1);
INSERT INTO bikeshedapp_bike VALUES (11, 'M', '2017-01-16 12:12:36.366495-05', 'Altum', 'Progress. Sometimes it happens incrementally—small advancements moving things forward.', 'The new Altum series from Parlee represents both types of progress. The modern tube shaping, the cutting-edge craftsmanship, even the Altum name all leave an immediate, unmistakable impression: this is something new.', 'uploads/2017altum34.jpg', 25, 4799.99, 4, 1);
INSERT INTO bikeshedapp_bike VALUES (12, 'R', '2017-01-16 12:12:36.366495-05', 'TTIR', 'THE ALL-NEW TTIR TURNS BRAKING INTO A POSITIVE FORCE.', 'The World’s fastest triathlon disc bike is ready to help you crush your next race. Here’s why: traditional rim brakes force you to brake early and lose speed in corners and descents.', 'uploads/TTiR-Disc-34.jpg', 25, 1799.99, 4, 1);

INSERT INTO bikeshedapp_bike VALUES (13, 'H', '2017-01-16 12:12:36.366495-05', 'XENITH ENDURA SPORT', 'High performance carbon fiber composite frame with tapered headtube and PF30 BB shell', 'Jamis keeps the cockpit components in their own hands including Ergo 6061 aluminum handlebars and stem, with the addition of a carbon fiber seatpost...', 'uploads/xenith.jpg', 25, 1098.99, 5, 1);
INSERT INTO bikeshedapp_bike VALUES (14, 'M', '2017-01-16 12:12:36.366495-05', 'XENITH TEAM BIKE 2015', 'Jamis Road Dyad Supreme M40/M30 Monocoque Carbon Fiber Frame', 'The Xenith Team is crowned king of Jamis’s “pro-level” road bikes, being proven under the legs of the top dogs themselves in Jamis/Sutter Home men’s pro squad and Colavita/Forno D’Asolo women’s pro team, as both teams topped USA Cycling’s 2011 NRC calendar week after week.', 'uploads/G0002CU0.jpg', 25, 3198.99, 5, 1);
INSERT INTO bikeshedapp_bike VALUES (15, 'R', '2017-01-16 12:12:36.366495-05', 'NEMESIS 650 RACE BIKE 2014', 'Triple butted aluminum frame features a tapered head tube and responsive geometry', 'The triple-butted aluminum frame of the Jamis Nemesis Race bike is exceedingly light and responsive. With a tapered headtube, and oversized chainstays, it offers stability and control in a light and affordable package.', 'uploads/G0002CUU.jpg', 25, 1098.99, 5, 1);

SELECT setval('bikeshedapp_bike_id_seq', (SELECT MAX(id) FROM bikeshedapp_bike)+1);
