# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshedapp', '0003_auto_20170114_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
