# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshedapp', '0004_auto_20170114_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AlterField(
            model_name='bike',
            name='type',
            field=models.CharField(choices=[('', 'Select Type'), ('M', 'Mountain'), ('R', 'Road'), ('H', 'Hybrid')], max_length=1),
        ),
    ]
