# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshedapp', '0005_auto_20170114_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, default='None/no-img.png', upload_to='uploads/'),
        ),
    ]
